# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'WeiboSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'Toast-Swift'
  pod 'HandyJSON'

end
